# Generated by Django 6.0.2 on 2026-03-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollment_status',
            new_name='enrollement_status',
        ),
    ]
