# Generated by Django 6.0 on 2026-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_rename_enrollment_status_student_enrollement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_academic_level',
            field=models.CharField(choices=[('p.1', 'Primary 1'), ('P.2', 'Primary 2'), ('p.3', 'Primary 3'), ('p.4', 'Primary 4'), ('p.5', 'Primary 5')], max_length=10, verbose_name='Current Academic Level'),
        ),
    ]
